### ISSUE TITLE
IE vs Chrome

### ISSUE THREAD

**Issue by sibinpthomas** [geoff-codes/posix-unix-standard#2]
I failed at step 4 in Chrome when trying to provide the username password.
It worked in IE.

Maybe you can mention about the greater probability of success with IE in the ReadMe.

**Comment by geoff-nixon** [comment]
Which version of IE? (Which OS?)

**Comment by sibinpthomas** [comment]
IE10, Windows 8

**Comment by geoff-nixon** [comment]
I've added a note in re: this issue.
