### ISSUE TITLE
Delay in accessing PDF

### ISSUE THREAD

**Issue by ghenry** [geoff-codes/posix-unix-standard#3]
Just a quick note to say there must be a backend job that sync's the http basic password at https://www.opengroup.org/austin/restricted/? as it took about an hour to let me in.

Thanks.

**Comment by geoff-nixon** [comment]
I've added [a note to this effect](https://github.com/geoff-codes/posix-standard/commit/43b07588a04e71048fb0b1d54bc359eb283b1663#diff-04c6e90faac2675aa89e2176d2eec7d8R22). Do you think that should be sufficient?

**Comment by geoff-nixon** [comment]
Closing; I think that should be sufficient.
